<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Transactions Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #1e3a8a;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f3f4f6;
            font-weight: bold;
        }
        .amount {
            text-align: right;
        }
        .badge {
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .badge-success {
            background-color: #dcfce7;
            color: #166534;
        }
        .badge-danger {
            background-color: #fee2e2;
            color: #991b1b;
        }
        .footer {
            margin-top: 20px;
            font-size: 10px;
            text-align: right;
            color: #999;
        }
        .summary {
            margin-top: 20px;
            float: right;
            width: 250px;
        }
        .summary table {
            border: none;
        }
        .summary td {
            border: none;
            padding: 4px;
        }
        .summary .total-label {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>GCash Tracker - Transactions</h1>
        <p>Generated on {{ now()->format('M d, Y H:i:A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Type</th>
                <th class="amount">Amount</th>
                <th class="amount">Profit</th>
                <th class="amount">GCash Balance</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $transaction)
                <tr>
                    <td>{{ $transaction->transaction_date->format('M d, Y') }}</td>
                    <td>
                        <span class="badge {{ $transaction->type === 'cash-in' ? 'badge-success' : 'badge-danger' }}">
                            {{ strtoupper(str_replace('-', ' ', $transaction->type)) }}
                        </span>
                    </td>
                    <td class="amount">₱{{ number_format($transaction->amount, 2) }}</td>
                    <td class="amount">₱{{ number_format($transaction->fee_amount, 2) }}</td>
                    <td class="amount">₱{{ number_format($transaction->gcash_balance_after, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary">
        <table>
            <tr>
                <td class="total-label">Total Cash In:</td>
                <td class="amount">₱{{ number_format($transactions->where('type', 'cash-in')->sum('amount'), 2) }}</td>
            </tr>
            <tr>
                <td class="total-label">Total Cash Out:</td>
                <td class="amount">₱{{ number_format($transactions->where('type', 'cash-out')->sum('amount'), 2) }}</td>
            </tr>
            <tr>
                <td class="total-label" style="border-top: 1px solid #ddd;">Total Profit:</td>
                <td class="amount" style="border-top: 1px solid #ddd; font-weight: bold;">₱{{ number_format($transactions->sum('fee_amount'), 2) }}</td>
            </tr>
        </table>
    </div>

    <div style="clear: both;"></div>

    <div class="footer">
        Generated by GCash Tracker
    </div>
</body>
</html>
